services:
  mongodb:
    image: mongo:latest
    container_name: crud-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
    - "27017:27017"
    networks:
    - crud-network

  backend:
    image: sairathod/crud-dd-task-backend:latest
    container_name: crud-backend
    ports:
    - "8081:8081"
    depends_on:
      - mongodb
    networks:
    - crud-network

  frontend:
    image: sairathod/crud-dd-task-frontend:latest
    container_name: crud-frontend
    ports:
    - "80:80"
    depends_on:
      - backend
    networks:
    - crud-network

volumes:
  mongodb_data:
networks:
  crud-network:
